---
# add open-iscsi for PV storage such as OpenEBS or Longhorn
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
  tasks:
    - name: install open-iscsi
      apt:
        name: open-iscsi
        state: latest
        update_cache: yes
    - name: enable open-iscsi service
      ansible.builtin.service:
        name: open-iscsi
        enabled: yes
